name: trace-app-cs-plugin
description: Plug-in para telemetria.
types:
- app
inputs:
- label: "Type"
  type: text
  name: "exporter_type"
  default: "Jaeger"
  items:
    - "Jaeger"
    - "OTLP"
    - "X-Ray"
    - "X-Ray - Daemon"
- label: "Server"
  type: text
  name: "server"
  default: ""
- label: "Port"
  type: text
  name: "port"
  default: ""

computedInputs: 
  "package": "{% if inputs.exporter_type == 'X-Ray - Daemon' %}{{'StackSpot.Tracing.XRay'}}{% else %}{{'StackSpot.Tracing'}}{% endif %}"
  "using": "{% if inputs.exporter_type == 'X-Ray - Daemon' %}{{'using StackSpot.Tracing.XRay;'}}{% else %}{{'using StackSpot.Tracing;'}}{% endif %}"
  "service": "{% if inputs.exporter_type == 'X-Ray - Daemon' %}{{'services.AddXRay(configuration);\n'}}{% else %}{{'services.AddOpenTelemetryTracing(configuration);\n'}}{% endif %}"
  "app": "{% if inputs.exporter_type == 'X-Ray - Daemon' %}{{'app.UseXRay(appName);\n'}}{% else %}{% endif %}"

hooks:
#package
  - type: run
    trigger: before-render
    commands:
      - dotnet add src/{{global_inputs.project_name}}.Application package {{computed_inputs.package}}
      - dotnet add src/{{global_inputs.project_name}}.Infrastructure package {{computed_inputs.package}}
#dependencyinjection
  - type: edit
    trigger: before-render
    path: "src/{{project_name}}.Application/Common/StackSpot/DependencyInjection.cs"
    changes:
      - search:
          string: "using"
          insert-before:
            value: "{{computed_inputs.using}}"
          when:
            not-exists: "{{computed_inputs.using}}"
      - search:
          string: "return services"
          insert-before:
            value: "{{computed_inputs.service}}"
          when:
            not-exists: "{{computed_inputs.service}}"
      - search:
          string: "return app"
          insert-before:
            snippet: snippets/src/Application/app.txt
          when:
            not-exists: "{computed_inputs.app}}"              
      - search:
          string: "return app"
          insert-before:
            value: "{{computed_inputs.app}}"
          when:
            not-exists: "{{computed_inputs.app}}"
#format
  - type: run
    trigger: after-render
    working-dir: src/{{project_name}}.Application
    commands:
      -  dotnet dotnet-format --include-generated

displayName: Trace

picture: "plugin.png"

category: backend, observability

compatibility:
  - net5.0
  - net6.0

about: about.md

usage: usage.md

useCase: useCase.md

implementation: implementation.md

technologies: [".NET", "C#", "Jaeger"]